# Generated by Django 5.0.7 on 2025-09-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_assetprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetprofile',
            name='auto_loan_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='assetprofile',
            name='credit_card_limit_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='assetprofile',
            name='delinquency_last12m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assetprofile',
            name='expense_monthly',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assetprofile',
            name='housing_loan_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='assetprofile',
            name='income_monthly',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assetprofile',
            name='investment_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='assetprofile',
            name='savings_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
