# Generated by Django 5.2.5 on 2025-09-03 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(choices=[('freelance', '프리랜서'), ('business', '사업자'), ('employee', '급여소득자'), ('mixed', '혼합소득')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthly_income_1', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monthly_income_2', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monthly_income_3', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monthly_income_4', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monthly_income_5', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monthly_income_6', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monthly_income_7', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monthly_income_8', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monthly_income_9', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monthly_income_10', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monthly_income_11', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monthly_income_12', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('predicted_monthly_income', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('predicted_yearly_income', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('confidence_level', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('income_volatility', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('seasonal_pattern', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('conservative', '보수형'), ('moderate', '균형형'), ('aggressive', '공격형')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_savings_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('emergency_fund_target', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('investment_target', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monthly_savings', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monthly_investment', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monthly_expenses', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('current_credit_score', models.IntegerField(default=0)),
                ('target_credit_score', models.IntegerField(default=0)),
                ('credit_improvement_plan', models.TextField(blank=True)),
                ('plan_description', models.TextField(blank=True)),
                ('risk_assessment', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_plans', to=settings.AUTH_USER_MODEL)),
                ('income_prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='plan.incomeprediction')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('expected_income', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('housing_expense', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('food_expense', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('transportation_expense', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('healthcare_expense', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('entertainment_expense', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('other_expenses', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('savings_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('investment_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('credit_card_payment', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('loan_payment', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('financial_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_plans', to='plan.financialplan')),
            ],
            options={
                'ordering': ['year', 'month'],
                'unique_together': {('financial_plan', 'year', 'month')},
            },
        ),
    ]
