# Generated by Django 5.2.5 on 2025-09-09 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('utilization_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('on_time_payment_ratio', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('credit_age_months', models.IntegerField(default=0)),
                ('hard_inquiries_12m', models.IntegerField(default=0)),
                ('credit_mix_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
