# Generated by Django 5.2.5 on 2025-09-17 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reward", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_order",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("is_correct", models.BooleanField(default=False)),
                ("points_awarded", models.IntegerField(default=0)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="reward.quizattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reward.quizquestion",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reward.quizoption",
                    ),
                ),
            ],
            options={
                "ordering": ["question__order", "id"],
            },
        ),
    ]
